#!/bin/bash

# Script d'aide pour les commits intelligents

echo "🚀 Système de Smart Commit - Aide"
echo ""
echo "📋 Scripts disponibles:"
echo ""
echo "1. 🔧 smart-commit.js (interactif avec confirmation)"
echo "   Usage: node scripts/smart-commit.js commit [patch|minor|major]"
echo "   - Analyse les fichiers modifiés"
echo "   - Génère un message intelligent"
echo "   - Demande confirmation avant commit"
echo "   - Ne change la version QUE si le commit réussit"
echo ""
echo "2. ⚡ quick-commit.sh (rapide avec confirmation)"
echo "   Usage: ./scripts/quick-commit.sh [patch|minor|major] [message]"
echo "   - Commit rapide avec gestion de version"
echo "   - Affiche les changements avant commit"
echo "   - Restaure les versions en cas d'échec"
echo ""
echo "3. 🚀 commit-all.sh (ultra-rapide)"
echo "   Usage: ./scripts/commit-all.sh [message]"
echo "   - Ajoute TOUS les fichiers modifiés"
echo "   - Commit immédiat sans confirmation"
echo "   - Version patch automatique"
echo ""
echo "📝 Types de version:"
echo "   - patch: 1.0.0 → 1.0.1 (corrections, petits changements)"
echo "   - minor: 1.0.0 → 1.1.0 (nouvelles fonctionnalités)"
echo "   - major: 1.0.0 → 2.0.0 (changements majeurs)"
echo ""
echo "💡 Exemples d'utilisation:"
echo "   # Commit interactif (recommandé)"
echo "   node scripts/smart-commit.js commit"
echo ""
echo "   # Commit rapide avec version minor"
echo "   ./scripts/quick-commit.sh minor \"Ajout du système de messages\""
echo ""
echo "   # Commit ultra-rapide"
echo "   ./scripts/commit-all.sh \"Fix bug login\""
echo ""
echo "🔒 Sécurité:"
echo "   - Les versions ne sont mises à jour QUE si le commit réussit"
echo "   - Restauration automatique en cas d'échec"
echo "   - Sauvegarde des versions avant modification"
echo ""
echo "📊 Version actuelle:"
if [ -f "dev/package.json" ]; then
    CURRENT_VERSION=$(node -p "require('./dev/package.json').version" 2>/dev/null || echo "Inconnue")
    echo "   $CURRENT_VERSION"
else
    echo "   Impossible de récupérer la version"
fi
